; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[env:esp32s3]
platform = espressif32
board = esp32-s3-devkitc-1
framework = arduino
board_build.flash_size = 8MB
board_upload.flash_size = 8MB
board_build.flash_mode = qio
board_build.arduino.memory_type = qio_qspi
board_build.partitions = partitions.csv
monitor_speed = 115200
upload_speed = 921600
board_build.filesystem = spiffs
build_flags =
	-DCONFIG_ESP_WIFI_STATIC_RX_BUFFER_NUM=3
	-DCONFIG_ESP_WIFI_DYNAMIC_RX_BUFFER_NUM=6
	-DCONFIG_ESP_WIFI_RX_BA_WIN=3
	-DCONFIG_LWIP_TCPIP_RECVMBOX_SIZE=16
	-DCONFIG_HTTPD_WS_SUPPORT=1
	-DCONFIG_MBEDTLS_DYNAMIC_FREE_CONFIG_DATA=1
	-DCONFIG_MBEDTLS_SSL_IN_CONTENT_LEN=8192
	-DCONFIG_MBEDTLS_SSL_OUT_CONTENT_LEN=2048
	-DCONFIG_LWIP_LOCAL_HOSTNAME=\"mimiclaw\"
lib_deps =
